# Minimal SearXNG Configuration for OpenWebUI
# Based on https://docs.searxng.org/admin/settings/settings.html

use_default_settings: true

general:
  instance_name: "OpenWebUI Search"
  enable_metrics: false

server:
  secret_key: "c9b92c6e588b92a9919544a5858c28a315187087c784e73993a17210ad3805ee"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

ui:
  default_theme: simple
  query_in_title: false
