# SearXNG Configuration for OpenWebUI Integration
# This is a minimal configuration optimized for OpenWebUI RAG web search

general:
  debug: false
  instance_name: "OpenWebUI Search"

search:
  safe_search: 0  # 0=off, 1=moderate, 2=strict
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json  # Required for OpenWebUI integration

server:
  secret_key: "change_this_secret_key_in_production"  # Generate with: openssl rand -hex 32
  limiter: false  # Disable rate limiting for localhost
  image_proxy: true
  method: "GET"

ui:
  static_use_hash: true
  default_theme: simple
  query_in_title: false
  infinite_scroll: false

# Enable popular search engines
# Remove engines you don't want or add more from SearXNG docs
engines:
  - name: google
    engine: google
    shortcut: g

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: bing
    engine: bing
    shortcut: b

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: github
    engine: github
    shortcut: gh

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so

  - name: arxiv
    engine: arxiv
    shortcut: ar

  - name: reddit
    engine: reddit
    shortcut: re

  - name: youtube
    engine: youtube_noapi
    shortcut: yt
    disabled: true  # Enable if you want video results

enabled_plugins: []

doi_resolvers: {}

default_doi_resolver: 'oadoi.org'
